print("#############################")
print("#                           #")
print("#   Siti Ratna Dwinta Sari  #")
print("#       2310817120002       #")
print("#                           #")
print("#############################")