nama=input("Nama                    : ")
nim= input("NIM                     : ")
kls= input("Kelas Paralel           : ")
ttl= input("Tempat/Tanggal Lahir    : ")
alm= input("Alamat                  : ")
hby= input("Hobby                   : ")
nohp=input("No.HP                   : ")
print("\n")
print("Nama                    :", nama)
print("NIM                     :", nim)
print("Kelas Paralel           :", kls)
print("Temapat/Tanggal Lahir   :", ttl)
print("Alamat                  :", alm)
print("Hobby                   :", hby)
print("No. HP                  :", nohp)